version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend

  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - backend
    environment:
      - MONGO_URL=mongodb://mongodb:27017/tarefas?authSource=admin

networks:
  backend:
    driver: bridge