version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend

  backend:
    build:
      context: .
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - backend
    environment:
      MONGO_URL: mongodb://mongo:27017/tarefas?directConnection=true

networks:
  backend:
    driver: bridge